name: Merge to dev or hotfix

on:
  push:
    branches:
      - dev
      - hotfix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22'

jobs:
  create-rc:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Create deployooor app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_APP_PK }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 1

      # setup pnpm first
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump versions
        env:
          args: ${{ github.ref_name == 'dev' && '--prerelease' || '' }}
        run: pnpm turboversion ${{ env.args }}

      - name: Push changes and tags
        run: |
          git config --local user.email "deployooor@nexusmutual.io"
          git config --local user.name "Version bumpooor"
          git push origin ${{ github.ref_name }} --follow-tags
